version: "3.4"

services:
  mongodb:
    image: "mongo:4.0"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  server:
    network_mode: host
    build:
      context: "./server"
    command: node cluster.js
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    volumes:
      - ./static:/usr/api/static
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  front:
    restart: always
    build:
      context: "./front"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d

